using FilterPresetConverter.Models;
using FilterPresetConverter.Services;
using Newtonsoft.Json;

namespace FilterPresetConverter.Tests;

/// <summary>
/// 转换测试类
/// </summary>
public class ConversionTest
{
    private readonly BrsetToBsfConverter _converter = new();

    /// <summary>
    /// 运行所有测试
    /// </summary>
    public void RunAllTests()
    {
        Console.WriteLine("=== BRSET to BSF 转换测试 ===\n");

        // 测试1: 使用包含新字段的brset文件
        TestFile("G:\\曲包更新器\\Settings\\【1.菜鸡包】最新600首每秒0.5-2方块难度的高评分歌曲 更新至[[日期]]@WGzeyu.brset");

        Console.WriteLine("\n" + new string('=', 50) + "\n");

        // 测试2: 使用包含标签和上传时间的brset文件
        TestFile("G:\\曲包更新器\\Settings\\手动新ACG-Tag.brset");

        Console.WriteLine("\n" + new string('=', 50) + "\n");

        // 测试3: 构造测试数据验证所有字段
        TestAllFields();

        Console.WriteLine("\n" + new string('=', 50) + "\n");

        // 测试4: 测试搜索过滤功能
        TestSearchFilter();
    }

    /// <summary>
    /// 测试指定文件
    /// </summary>
    public void TestFile(string filePath)
    {
        Console.WriteLine($"测试文件: {Path.GetFileName(filePath)}");
        Console.WriteLine(new string('-', 60));

        if (!File.Exists(filePath))
        {
            Console.WriteLine($"文件不存在: {filePath}");
            return;
        }

        var brset = _converter.LoadBrsetFile(filePath);
        if (brset == null)
        {
            Console.WriteLine("加载brset文件失败");
            return;
        }

        var result = _converter.Convert(brset, Path.GetFileNameWithoutExtension(filePath));

        Console.WriteLine($"转换结果: {(result.Success ? "成功" : "失败")}");
        Console.WriteLine($"消息: {result.Message}");

        if (result.Warnings.Count > 0)
        {
            Console.WriteLine("\n警告:");
            foreach (var warning in result.Warnings)
            {
                Console.WriteLine($"  - {warning}");
            }
        }

        if (result.SkippedItems.Count > 0)
        {
            Console.WriteLine("\n跳过的项目:");
            foreach (var item in result.SkippedItems)
            {
                Console.WriteLine($"  - {item}");
            }
        }

        if (result.Preset != null)
        {
            Console.WriteLine($"\n转换后的条件 ({result.Preset.Groups.Sum(g => g.Conditions.Count)} 个):");
            foreach (var group in result.Preset.Groups)
            {
                Console.WriteLine($"\n  组: {group.Name}");
                foreach (var condition in group.Conditions)
                {
                    var valueStr = condition.Value switch
                    {
                        ResultLimitValue rlv => $"{rlv.Count}首",
                        DateTime dt => dt.ToString("yyyy-MM-dd"),
                        _ => condition.Value?.ToString() ?? "null"
                    };
                    Console.WriteLine($"    [{condition.Type}] {condition.Type}: {valueStr}");
                }
            }

            // 输出JSON以便检查
            Console.WriteLine("\n生成的BSF JSON:");
            var json = _converter.ToBsfJson(result.Preset);
            Console.WriteLine(json);
        }
    }

    /// <summary>
    /// 测试所有字段映射
    /// </summary>
    public void TestAllFields()
    {
        Console.WriteLine("测试所有字段映射");
        Console.WriteLine(new string('-', 60));

        // 构造包含所有字段的测试brset
        var testBrset = new BrsetPreset();

        // BeatSaver节点
        testBrset.BeatSaver = new BeatSaverSection
        {
            BPM = new MinMaxSection { Enabled = true, Min = "60", Max = "180" },
            NPS = new MinMaxSection { Enabled = true, Min = "2", Max = "10" },
            Duration = new MinMaxSection { Enabled = true, Min = "60", Max = "300" },
            UploadTime = new MinMaxSection { Enabled = true, Min = "1670774400", Max = "" }, // Unix时间戳
            Rating = new MinMaxSection { Enabled = true, Min = "80", Max = "" },
            AutoGenerated = new EnabledValueSection { Enabled = true, AutoGeneratedValue = false },
            Ranked = new EnabledValueSection { Enabled = true, RankedValue = true },
            RequiredMods = new EnabledContentSection { Enabled = true, Content = "Chroma,Noodle" },
            ExcludeMods = new EnabledContentSection { Enabled = true, Content = "Me" }
        };

        // 筛选项目节点
        testBrset.FilterItems = new FilterItemsSection
        {
            // 基本字段
            BPM = new MinMaxSection { Enabled = true, Min = "100", Max = "160" },
            NPS = new MinMaxSection { Enabled = true, Min = "3", Max = "8" },
            SongDuration = new MinMaxSection { Enabled = true, Min = "120", Max = "360" },
            UploadTime = new MinMaxSection { Enabled = true, Min = "30", Max = "" }, // 天数偏移

            // 统计字段
            Downloads = new MinMaxSection { Enabled = true, Min = "100", Max = "" },
            Plays = new MinMaxSection { Enabled = true, Min = "50", Max = "" },
            Upvotes = new MinMaxSection { Enabled = true, Min = "20", Max = "" },
            UpvoteRatio = new MinMaxSection { Enabled = true, Min = "85", Max = "" },
            Downvotes = new MinMaxSection { Enabled = true, Min = "", Max = "10" },
            DownvoteRatio = new MinMaxSection { Enabled = true, Min = "", Max = "15" },
            Score = new MinMaxSection { Enabled = true, Min = "75", Max = "" },
            SageScore = new MinMaxSection { Enabled = true, Min = "2", Max = "" },
            MaxScore = new MinMaxSection { Enabled = true, Min = "100", Max = "" },

            // 难度参数
            NJS = new MinMaxSection { Enabled = true, Min = "10", Max = "20" },
            Offset = new MinMaxSection { Enabled = true, Min = "-0.5", Max = "0.5" },
            Bombs = new MinMaxSection { Enabled = true, Min = "0", Max = "50" },
            Events = new MinMaxSection { Enabled = true, Min = "100", Max = "" },

            // 新增字段
            Walls = new MinMaxSection { Enabled = true, Min = "0", Max = "20" },
            MapDuration = new MinMaxSection { Enabled = true, Min = "60", Max = "300" },
            Notes = new MinMaxSection { Enabled = true, Min = "100", Max = "1000" },
            NoteCount = new MinMaxSection { Enabled = true, Min = "50", Max = "" },
            VerifyErrors = new MinMaxSection { Enabled = true, Min = "0", Max = "5" },
            VerifyWarnings = new MinMaxSection { Enabled = true, Min = "0", Max = "10" },
            VerifyResets = new MinMaxSection { Enabled = true, Min = "0", Max = "3" },

            // 内容字段
            UploaderId = new EnabledContentSection { Enabled = true, Content = "12345" },
            UploaderName = new EnabledContentSection { Enabled = true, Content = "TestMapper" },
            IncludeMode = new EnabledContentSection { Enabled = true, Content = "Standard" },
            IncludeDifficulty = new EnabledContentSection { Enabled = true, Content = "Expert,ExpertPlus" },
            RequiredMods = new EnabledContentSection { Enabled = true, Content = "Chroma" },
            ExcludeMods = new EnabledContentSection { Enabled = true, Content = "Me,Ne,CustomMod1" },  // 包含自定义Mod

            // 标签
            Tags = new TagsSection
            {
                Include = new TagFilterSection { Enabled = true, Content = "anime,kpop" },
                Exclude = new TagFilterSection { Enabled = true, Content = "comedy-meme" }
            },

            // 其他
            AutoGenerated = new EnabledValueSection { Enabled = true, AutoGeneratedValue = false },
            Ranked = new EnabledValueSection { Enabled = true, RankedValue = true },
            Stars = new MinMaxSection { Enabled = true, Min = "3", Max = "8" }
        };

        // ScoreSaber节点
        testBrset.ScoreSaber = new ScoreSaberSection
        {
            Difficulty = new MinMaxSection { Enabled = true, Min = "4", Max = "10" }
        };

        // 下载限制
        testBrset.DownloadLimit = new DownloadLimitSection
        {
            LimitCount = new EnabledContentSection { Enabled = true, Content = "100" }
        };

        // 执行转换
        var result = _converter.Convert(testBrset, "全字段测试");

        Console.WriteLine($"转换结果: {(result.Success ? "成功" : "失败")}");
        Console.WriteLine($"消息: {result.Message}");
        Console.WriteLine($"转换的条件数量: {result.Preset?.Groups.Sum(g => g.Conditions.Count) ?? 0}");

        if (result.Preset != null)
        {
            Console.WriteLine("\n转换后的条件详情:");
            var expectedFields = new Dictionary<string, bool>
            {
                // 基本字段
                ["MinBpm"] = false,
                ["MaxBpm"] = false,
                ["MinNps"] = false,
                ["MaxNps"] = false,
                ["MinDuration"] = false,
                ["MaxDuration"] = false,
                ["MinUploadedDate"] = false,
                ["MaxUploadedDate"] = false,
                // 统计字段
                ["MinDownloads"] = false,
                ["MaxDownloads"] = false,
                ["MinPlays"] = false,
                ["MaxPlays"] = false,
                ["MinUpvotes"] = false,
                ["MaxUpvotes"] = false,
                ["MinUpvoteRatio"] = false,
                ["MaxUpvoteRatio"] = false,
                ["MinDownvotes"] = false,
                ["MaxDownvotes"] = false,
                ["MinDownvoteRatio"] = false,
                ["MaxDownvoteRatio"] = false,
                ["MinScore"] = false,
                ["MaxScore"] = false,
                ["MinSageScore"] = false,
                ["MaxSageScore"] = false,
                ["MinMaxScore"] = false,
                ["MaxMaxScore"] = false,
                // 难度参数
                ["MinNjs"] = false,
                ["MaxNjs"] = false,
                ["MinOffset"] = false,
                ["MaxOffset"] = false,
                ["MinBombs"] = false,
                ["MaxBombs"] = false,
                ["MinEvents"] = false,
                ["MaxEvents"] = false,
                // 新增字段
                ["MinObstacles"] = false,
                ["MaxObstacles"] = false,
                ["MinSeconds"] = false,
                ["MaxSeconds"] = false,
                ["MinNotes"] = false,
                ["MaxNotes"] = false,
                ["MinParityErrors"] = false,
                ["MaxParityErrors"] = false,
                ["MinParityWarns"] = false,
                ["MaxParityWarns"] = false,
                ["MinParityResets"] = false,
                ["MaxParityResets"] = false,
                // 内容字段
                ["UploaderName"] = false,
                ["Characteristic"] = false,
                ["Difficulty"] = false,
                // 标签
                ["Tags"] = false,
                ["ExcludeTags"] = false,
                // Mod
                ["Chroma"] = false,
                ["Ne"] = false,
                ["Me"] = false,
                // 其他
                ["Ranked"] = false,
                ["Automapper"] = false,
                ["ResultLimit"] = false,
                ["MinSsStars"] = false,
                ["MaxSsStars"] = false
            };

            foreach (var group in result.Preset.Groups)
            {
                foreach (var condition in group.Conditions)
                {
                    var typeName = condition.Type.ToString();
                    if (expectedFields.ContainsKey(typeName))
                    {
                        expectedFields[typeName] = true;
                        Console.WriteLine($"  ✓ {typeName}: {condition.Value}");
                    }
                    else
                    {
                        Console.WriteLine($"  ? {typeName}: {condition.Value}");
                    }
                }
            }

            Console.WriteLine("\n字段覆盖检查:");
            var missing = expectedFields.Where(kv => !kv.Value).Select(kv => kv.Key).ToList();
            if (missing.Count == 0)
            {
                Console.WriteLine("  所有预期字段都已转换 ✓");
            }
            else
            {
                Console.WriteLine("  未转换的字段:");
                foreach (var field in missing)
                {
                    Console.WriteLine($"    ✗ {field}");
                }
            }
        }

        // 输出完整JSON
        if (result.Preset != null)
        {
            var outputPath = Path.Combine(Path.GetTempPath(), "test_output.bsf");
            _converter.SaveBsfFile(result.Preset, outputPath);
            Console.WriteLine($"\n测试输出已保存到: {outputPath}");
        }
    }

    /// <summary>
    /// 测试搜索过滤功能
    /// </summary>
    public void TestSearchFilter()
    {
        Console.WriteLine("测试搜索过滤功能");
        Console.WriteLine(new string('-', 60));

        // 测试1: 全部搜索(无范围选项)
        Console.WriteLine("\n--- 测试1: 全部搜索(无范围选项) ---");
        var test1 = new BrsetPreset
        {
            SearchFilter = new SearchFilterSection
            {
                SearchContent = "Camellia",
                SearchEnabled = true,
                SearchTitle = false,
                SearchSongName = false,
                SearchAuthor = false,
                SearchMapper = false,
                SearchDescription = false
            }
        };
        var result1 = _converter.Convert(test1, "全部搜索测试");
        Console.WriteLine($"转换结果: {result1.Message}");
        foreach (var cond in result1.Preset?.Groups.SelectMany(g => g.Conditions) ?? new List<FilterCondition>())
        {
            Console.WriteLine($"  [{cond.Type}] {cond.Value}");
        }

        // 测试2: 搜索歌名
        Console.WriteLine("\n--- 测试2: 搜索歌名 ---");
        var test2 = new BrsetPreset
        {
            SearchFilter = new SearchFilterSection
            {
                SearchContent = "Miku",
                SearchEnabled = true,
                SearchTitle = false,
                SearchSongName = true,
                SearchAuthor = false,
                SearchMapper = false,
                SearchDescription = false
            }
        };
        var result2 = _converter.Convert(test2, "歌名搜索测试");
        Console.WriteLine($"转换结果: {result2.Message}");
        foreach (var cond in result2.Preset?.Groups.SelectMany(g => g.Conditions) ?? new List<FilterCondition>())
        {
            Console.WriteLine($"  [{cond.Type}] {cond.Value}");
        }

        // 测试3: 多个搜索范围
        Console.WriteLine("\n--- 测试3: 多个搜索范围(标题+作者) ---");
        var test3 = new BrsetPreset
        {
            SearchFilter = new SearchFilterSection
            {
                SearchContent = "Camellia",
                SearchEnabled = true,
                SearchTitle = true,
                SearchSongName = false,
                SearchAuthor = true,
                SearchMapper = false,
                SearchDescription = false
            }
        };
        var result3 = _converter.Convert(test3, "多范围搜索测试");
        Console.WriteLine($"转换结果: {result3.Message}");
        foreach (var cond in result3.Preset?.Groups.SelectMany(g => g.Conditions) ?? new List<FilterCondition>())
        {
            Console.WriteLine($"  [{cond.Type}] {cond.Value}");
        }

        // 测试4: 搜索开关关闭
        Console.WriteLine("\n--- 测试4: 搜索开关关闭 ---");
        var test4 = new BrsetPreset
        {
            SearchFilter = new SearchFilterSection
            {
                SearchContent = "Test",
                SearchEnabled = false,
                SearchTitle = true,
                SearchSongName = true
            }
        };
        var result4 = _converter.Convert(test4, "关闭搜索测试");
        Console.WriteLine($"转换结果: {result4.Message}");
        Console.WriteLine($"条件数量: {result4.Preset?.Groups.Sum(g => g.Conditions.Count) ?? 0}");

        // 测试5: 搜索谱师
        Console.WriteLine("\n--- 测试5: 搜索谱师 ---");
        var test5 = new BrsetPreset
        {
            SearchFilter = new SearchFilterSection
            {
                SearchContent = "Rigid",
                SearchEnabled = true,
                SearchTitle = false,
                SearchSongName = false,
                SearchAuthor = false,
                SearchMapper = true,
                SearchDescription = false
            }
        };
        var result5 = _converter.Convert(test5, "谱师搜索测试");
        Console.WriteLine($"转换结果: {result5.Message}");
        foreach (var cond in result5.Preset?.Groups.SelectMany(g => g.Conditions) ?? new List<FilterCondition>())
        {
            Console.WriteLine($"  [{cond.Type}] {cond.Value}");
        }

        // 测试6: 搜索介绍
        Console.WriteLine("\n--- 测试6: 搜索介绍 ---");
        var test6 = new BrsetPreset
        {
            SearchFilter = new SearchFilterSection
            {
                SearchContent = "FC养成",
                SearchEnabled = true,
                SearchTitle = false,
                SearchSongName = false,
                SearchAuthor = false,
                SearchMapper = false,
                SearchDescription = true
            }
        };
        var result6 = _converter.Convert(test6, "介绍搜索测试");
        Console.WriteLine($"转换结果: {result6.Message}");
        foreach (var cond in result6.Preset?.Groups.SelectMany(g => g.Conditions) ?? new List<FilterCondition>())
        {
            Console.WriteLine($"  [{cond.Type}] {cond.Value}");
        }

        Console.WriteLine("\n搜索过滤测试完成 ✓");
    }
}