using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FilterPresetConverter.Models
{
    /// <summary>
    /// BRSET预设格式模型 (BeatSpider预设格式)
    /// </summary>
    public class BrsetPreset
    {
        [JsonProperty("下载方式选择")]
        public int DownloadMethod { get; set; }

        [JsonProperty("BeatSaver")]
        public BeatSaverSection BeatSaver { get; set; } = new();

        [JsonProperty("谱师个人页面")]
        public MapperProfileSection MapperProfile { get; set; } = new();

        [JsonProperty("本地数据缓存")]
        public LocalCacheSection LocalCache { get; set; } = new();

        [JsonProperty("ScoreSaber")]
        public ScoreSaberSection ScoreSaber { get; set; } = new();

        [JsonProperty("BEASTSABER")]
        public BeastSaberSection BeastSaber { get; set; } = new();

        [JsonProperty("歌曲列表")]
        public SongListSection SongList { get; set; } = new();

        [JsonProperty("手动")]
        public ManualSection Manual { get; set; } = new();

        [JsonProperty("搜索过滤")]
        public SearchFilterSection SearchFilter { get; set; } = new();

        [JsonProperty("本地歌曲目录")]
        public LocalSongDirectorySection LocalSongDirectory { get; set; } = new();

        [JsonProperty("保存方式")]
        public SaveMethodSection SaveMethod { get; set; } = new();

        [JsonProperty("筛选项目")]
        public FilterItemsSection FilterItems { get; set; } = new();

        [JsonProperty("下载限制")]
        public DownloadLimitSection DownloadLimit { get; set; } = new();

        [JsonProperty("封面标签")]
        public CoverTagSection CoverTag { get; set; } = new();
    }

    public class BeatSaverSection
    {
        [JsonProperty("搜索词")]
        public string SearchTerm { get; set; } = "";

        [JsonProperty("开始页数")]
        public string StartPage { get; set; } = "";

        [JsonProperty("下载方式")]
        public int DownloadMethod { get; set; }

        [JsonProperty("自动生成")]
        public EnabledValueSection AutoGenerated { get; set; } = new();

        [JsonProperty("排位曲")]
        public EnabledValueSection Ranked { get; set; } = new();

        [JsonProperty("全难度")]
        public EnabledValueSection AllDifficulty { get; set; } = new();

        [JsonProperty("BPM")]
        public MinMaxSection BPM { get; set; } = new();

        [JsonProperty("方块密度")]
        public MinMaxSection NPS { get; set; } = new();

        [JsonProperty("歌曲时长")]
        public MinMaxSection Duration { get; set; } = new();

        [JsonProperty("上传时间")]
        public MinMaxSection UploadTime { get; set; } = new();

        [JsonProperty("总评分")]
        public MinMaxSection Rating { get; set; } = new();

        [JsonProperty("需求组件")]
        public EnabledContentSection RequiredMods { get; set; } = new();

        [JsonProperty("排除组件")]
        public EnabledContentSection ExcludeMods { get; set; } = new();
    }

    public class MapperProfileSection
    {
        [JsonProperty("地址")]
        public string Url { get; set; } = "";
    }

    public class LocalCacheSection
    {
        [JsonProperty("选择本地缓存")]
        public bool UseLocalCache { get; set; }

        [JsonProperty("选择在线缓存")]
        public bool UseOnlineCache { get; set; }
    }

    public class ScoreSaberSection
    {
        [JsonProperty("难度")]
        public MinMaxSection Difficulty { get; set; } = new();
    }

    public class BeastSaberSection
    {
        [JsonProperty("地址")]
        public string Url { get; set; } = "";

        [JsonProperty("开始页数")]
        public string StartPage { get; set; } = "";
    }

    public class SongListSection
    {
        [JsonProperty("路径")]
        public string Path { get; set; } = "";
    }

    public class ManualSection
    {
        [JsonProperty("手动下载歌曲")]
        public string ManualDownload { get; set; } = "";
    }

    public class SearchFilterSection
    {
        [JsonProperty("搜索内容")]
        public string SearchContent { get; set; } = "";

        [JsonProperty("搜索开关")]
        public bool SearchEnabled { get; set; }

        [JsonProperty("搜索标题")]
        public bool SearchTitle { get; set; }

        [JsonProperty("搜索歌名")]
        public bool SearchSongName { get; set; }

        [JsonProperty("搜索作者")]
        public bool SearchAuthor { get; set; }

        [JsonProperty("搜索谱师")]
        public bool SearchMapper { get; set; }

        [JsonProperty("搜索介绍")]
        public bool SearchDescription { get; set; }

        [JsonProperty("高级搜索")]
        public bool AdvancedSearch { get; set; }

        [JsonProperty("正则搜索")]
        public bool RegexSearch { get; set; }
    }

    public class LocalSongDirectorySection
    {
        [JsonProperty("目录")]
        public string Directory { get; set; } = "";

        [JsonProperty("跳过")]
        public string Skip { get; set; } = "";

        [JsonProperty("现行子夹")]
        public int CurrentSubfolder { get; set; }
    }

    public class SaveMethodSection
    {
        [JsonProperty("歌曲列表")]
        public EnabledPathSection SongList { get; set; } = new();

        [JsonProperty("下载歌曲")]
        public EnabledPathSection DownloadSongs { get; set; } = new();

        [JsonProperty("命名方式")]
        public NamingMethodSection NamingMethod { get; set; } = new();
    }

    public class NamingMethodSection
    {
        [JsonProperty("英文")]
        public bool English { get; set; }

        [JsonProperty("内容")]
        public string Content { get; set; } = "";
    }

    public class FilterItemsSection
    {
        [JsonProperty("上传者ID")]
        public EnabledContentSection UploaderId { get; set; } = new();

        [JsonProperty("上传者名称")]
        public EnabledContentSection UploaderName { get; set; } = new();

        [JsonProperty("需求组件")]
        public EnabledContentSection RequiredMods { get; set; } = new();

        [JsonProperty("排除组件")]
        public EnabledContentSection ExcludeMods { get; set; } = new();

        [JsonProperty("包含模式")]
        public EnabledContentSection IncludeMode { get; set; } = new();

        [JsonProperty("包含难度")]
        public EnabledContentSection IncludeDifficulty { get; set; } = new();

        [JsonProperty("下载量")]
        public MinMaxSection Downloads { get; set; } = new();

        [JsonProperty("游戏次数")]
        public MinMaxSection Plays { get; set; } = new();

        [JsonProperty("点赞数量")]
        public MinMaxSection Upvotes { get; set; } = new();

        [JsonProperty("点赞比例")]
        public MinMaxSection UpvoteRatio { get; set; } = new();

        [JsonProperty("点踩数量")]
        public MinMaxSection Downvotes { get; set; } = new();

        [JsonProperty("点踩比例")]
        public MinMaxSection DownvoteRatio { get; set; } = new();

        [JsonProperty("总评分")]
        public MinMaxSection Score { get; set; } = new();

        [JsonProperty("标签")]
        public TagsSection Tags { get; set; } = new();

        [JsonProperty("Sage分数")]
        public MinMaxSection SageScore { get; set; } = new();

        [JsonProperty("最高分数")]
        public MinMaxSection MaxScore { get; set; } = new();

        [JsonProperty("自动生成")]
        public EnabledValueSection AutoGenerated { get; set; } = new();

        [JsonProperty("排位曲")]
        public EnabledValueSection Ranked { get; set; } = new();

        [JsonProperty("筛选中文")]
        public EnabledOnlySection FilterChinese { get; set; } = new();

        [JsonProperty("BPM")]
        public MinMaxSection BPM { get; set; } = new();

        [JsonProperty("歌曲时长")]
        public MinMaxSection SongDuration { get; set; } = new();

        [JsonProperty("谱面时长")]
        public MinMaxSection MapDuration { get; set; } = new();

        [JsonProperty("节拍数量")]
        public MinMaxSection Notes { get; set; } = new();

        [JsonProperty("飞行速度")]
        public MinMaxSection NJS { get; set; } = new();

        [JsonProperty("偏移值")]
        public MinMaxSection Offset { get; set; } = new();

        [JsonProperty("方块数量")]
        public MinMaxSection NoteCount { get; set; } = new();

        [JsonProperty("方块密度")]
        public MinMaxSection NPS { get; set; } = new();

        [JsonProperty("炸弹数量")]
        public MinMaxSection Bombs { get; set; } = new();

        [JsonProperty("灯光事件")]
        public MinMaxSection Events { get; set; } = new();

        [JsonProperty("墙壁数量")]
        public MinMaxSection Walls { get; set; } = new();

        [JsonProperty("难度星级")]
        public MinMaxSection Stars { get; set; } = new();

        [JsonProperty("校验错误")]
        public MinMaxSection VerifyErrors { get; set; } = new();

        [JsonProperty("校验警告")]
        public MinMaxSection VerifyWarnings { get; set; } = new();

        [JsonProperty("校验重置")]
        public MinMaxSection VerifyResets { get; set; } = new();

        [JsonProperty("上传时间")]
        public MinMaxSection UploadTime { get; set; } = new();
    }

    public class DownloadLimitSection
    {
        [JsonProperty("限制数量")]
        public EnabledContentSection LimitCount { get; set; } = new();
    }

    public class CoverTagSection
    {
        [JsonProperty("总开关")]
        public EnabledOnlySection MasterSwitch { get; set; } = new();

        [JsonProperty("封面ACG预设")]
        public EnabledOnlySection ACGPreset { get; set; } = new();

        [JsonProperty("封面Token等待")]
        public EnabledOnlySection TokenWait { get; set; } = new();

        [JsonProperty("封面包含")]
        public EnabledContentSection Include { get; set; } = new();

        [JsonProperty("封面包含与")]
        public EnabledOnlySection IncludeAnd { get; set; } = new();

        [JsonProperty("封面包含或")]
        public EnabledOnlySection IncludeOr { get; set; } = new();

        [JsonProperty("封面排除")]
        public EnabledContentSection Exclude { get; set; } = new();

        [JsonProperty("封面排除与")]
        public EnabledOnlySection ExcludeAnd { get; set; } = new();

        [JsonProperty("封面排除或")]
        public EnabledOnlySection ExcludeOr { get; set; } = new();

        [JsonProperty("封面包含置信度")]
        public ContentOnlySection IncludeConfidence { get; set; } = new();

        [JsonProperty("封面排除置信度")]
        public ContentOnlySection ExcludeConfidence { get; set; } = new();
    }

    // 辅助类
    public class MinMaxSection
    {
        [JsonProperty("启用")]
        public bool Enabled { get; set; }

        [JsonProperty("min")]
        public string Min { get; set; } = "";

        [JsonProperty("max")]
        public string Max { get; set; } = "";
    }

    public class EnabledContentSection
    {
        [JsonProperty("启用")]
        public bool Enabled { get; set; }

        [JsonProperty("内容")]
        public string Content { get; set; } = "";
    }

    public class EnabledValueSection
    {
        [JsonProperty("启用")]
        public bool Enabled { get; set; }

        [JsonProperty("自动生成")]
        public bool AutoGeneratedValue { get; set; }

        [JsonProperty("排位曲")]
        public bool RankedValue { get; set; }

        // 为了向后兼容，Value属性返回任一非默认值
        [JsonIgnore]
        public bool Value
        {
            get => AutoGeneratedValue || RankedValue;
            set { AutoGeneratedValue = value; RankedValue = value; }
        }
    }

    public class EnabledPathSection
    {
        [JsonProperty("启用")]
        public bool Enabled { get; set; }

        [JsonProperty("路径")]
        public string Path { get; set; } = "";
    }

    public class EnabledOnlySection
    {
        [JsonProperty("启用")]
        public bool Enabled { get; set; }
    }

    public class ContentOnlySection
    {
        [JsonProperty("内容")]
        public string Content { get; set; } = "";
    }

    public class TagsSection
    {
        [JsonProperty("包含")]
        public TagFilterSection Include { get; set; } = new();

        [JsonProperty("排除")]
        public TagFilterSection Exclude { get; set; } = new();
    }

    public class TagFilterSection
    {
        [JsonProperty("启用")]
        public bool Enabled { get; set; }

        [JsonProperty("内容")]
        public string Content { get; set; } = "";

        [JsonProperty("与")]
        public bool And { get; set; }

        [JsonProperty("或")]
        public bool Or { get; set; }
    }
}